title: Remziye Tugba Țandără # your name (or website title) here
logo: "/images/last-cv.jpg?raw=true" <br><br> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A self-taught data analyst or <br>
  A biomedical engineering graduate who is passionate about data analytics. <br>
  I love working with data and I am looking to find a professional position that can echo this sentiment. <br><br>

  SQL ✔ <br>
  Python ✔ <br>
  R ✔ <br>
  Tableau ✔ <br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/remziye-tugba-tandara/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
